[tool.poetry]
name = "dnd5esheets"
version = "0.1.0"
description = "Character sheets for D&D 5e"
authors = ["Balthazar Rouberol <br@imap.cc>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-slugify = "^8.0.1"
alembic = "^1.11.2"
fastapi = "^0.101.0"
uvicorn = { extras = ["standard"], version = "^0.23.2" }
sqlalchemy = { extras = ["aiosqlite"], version = "^2.0.19" }
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
pydantic = "2.1.1"
python-multipart = "^0.0.6"
fastapi-jwt = "^0.1.12"
pydantic-settings = "^2.0.2"
sqladmin = "^0.13.0"
itsdangerous = "^2.1.2"
pygments = "^2.15.1"
orjson = "^3.9.3"
pyinstrument = "^4.5.1"
structlog = "^23.1.0"
asgi-correlation-id = "^4.2.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
ruff = "^0.0.282"
black = "^23.7.0"
types-passlib = "^1.7.7.12"
pytest = "^7.4.0"
httpx = "^0.24.1"
beautifulsoup4 = "^4.12.2"
types-python-slugify = "^8.0.0.2"
pytest-asyncio = "^0.21.1"
logging-tree = "^1.9"
rich = "^13.5.2"

[tool.poetry.scripts]
dnd5esheets-cli = 'dnd5esheets.cli:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 102

[tool.pytest.ini_options]
# We ignore the deprecation warning thrown in passlib until https://foss.heptapod.net/python-libs/passlib/-/issues/148 is resolved
addopts = "-s -W ignore::DeprecationWarning:passlib.utils:854"
testpaths = ["dnd5esheets/tests"]

[tool.mypy]
ignore_missing_imports = true
