[tool.poetry]
name = "dnd5esheets"
version = "0.1.0"
description = "Character sheets for D&D 5e"
authors = ["Balthazar Rouberol"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-slugify = "^8.0.1"
babel = "^2.12.1"
alembic = "^1.11.1"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.0"}
sqlalchemy = {extras = ["aiosqlite"], version = "^2.0.18"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
fastapi-jwt-auth = "^0.5.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
ruff = "^0.0.278"
black = "^23.7.0"
types-python-jose = "^3.3.4.7"
types-passlib = "^1.7.7.12"
pytest = "^7.4.0"
httpx = "^0.24.1"
beautifulsoup4 = "^4.12.2"

[tool.poetry.scripts]
dnd5esheets-cli = 'dnd5esheets.cli:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 102

[tool.pytest.ini_options]
addopts = "-s --disable-warnings"
testpaths = [
    "dnd5esheets/tests"
]

[tool.mypy]
ignore_missing_imports = true
