[tool.poetry]
name = "5esheets"
version = "0.1.0"
description = "Character sheets for D&D 5e"
authors = ["Balthazar Rouberol"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.3.2"
python-slugify = "^8.0.1"
babel = "^2.12.1"
flask-babel = "^3.1.0"
caribou = "^0.3.0"
peewee = "^3.16.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
