"""character_slug_unique_per_player

Revision ID: 3fb13bacd9e0
Revises: 75d60ad2f121
Create Date: 2023-07-19 19:39:11.403881

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fb13bacd9e0"
down_revision = "75d60ad2f121"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.create_unique_constraint("character_slug_unique_per_player", ["slug", "player_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.drop_constraint("character_slug_unique_per_player", type_="unique")

    # ### end Alembic commands ###
