"""user_password

Revision ID: 5300f3813592
Revises: 31dc8f2d4efb
Create Date: 2023-06-24 23:09:45.394891

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5300f3813592"
down_revision = "31dc8f2d4efb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column("player", sa.Column("hashed_password", sa.String(), nullable=False))
    op.create_index(op.f("ix_player_email"), "player", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_email"), table_name="player")
    op.drop_column("player", "hashed_password")
    op.drop_column("player", "email")
    # ### end Alembic commands ###
