"""add_equipment_models

Revision ID: ac918762ed96
Revises: 5300f3813592
Create Date: 2023-06-27 15:46:59.879959

"""
import sqlalchemy as sa
from alembic import op

from dnd5esheets.models import Json

# revision identifiers, used by Alembic.
revision = "ac918762ed96"
down_revision = "5300f3813592"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("json_data", Json(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_name"), ["name"], unique=True)

    op.create_table(
        "equipped_item",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("equipped", sa.Boolean(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipped_item")
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_name"))

    op.drop_table("item")
    # ### end Alembic commands ###
