"""enable_character_multiclassing

Revision ID: 6be04cbcbc82
Revises: 4e711ca20c98
Create Date: 2023-11-20 21:54:04.036403

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6be04cbcbc82"
down_revision = "4e711ca20c98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.drop_column("class")
        batch_op.drop_column("level")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.add_column(sa.Column("level", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("class", sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
