"""character_nullable_fields

Revision ID: 75d60ad2f121
Revises: cb612db24d70
Create Date: 2023-07-19 17:40:43.720445

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75d60ad2f121"
down_revision = "cb612db24d70"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.alter_column(
            "class", existing_type=sa.VARCHAR(length=80), nullable=True
        )
        batch_op.alter_column("level", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("json_data", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.alter_column("json_data", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("level", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "class", existing_type=sa.VARCHAR(length=80), nullable=False
        )

    # ### end Alembic commands ###
