"""add_equipment_models

Revision ID: c097e4aceca2
Revises: 5300f3813592
Create Date: 2023-06-27 14:33:38.690110

"""
import sqlalchemy as sa
from alembic import op

from dnd5esheets.models import Json

# revision identifiers, used by Alembic.
revision = "c097e4aceca2"
down_revision = "5300f3813592"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("json_data", Json(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_name"), ["name"], unique=True)

    op.create_table(
        "equipped_item",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("equipped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.add_column(sa.Column("equipment_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("character_equipment_id_equipment"),
            "equipment",
            ["equipment_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("character_equipment_id_equipment"), type_="foreignkey"
        )
        batch_op.drop_column("equipment_id")

    op.drop_table("equipped_item")
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_name"))

    op.drop_table("item")
    op.drop_table("equipment")
    # ### end Alembic commands ###
