name: Delete old container images

on:
  schedule:
    - cron: "0 0 1 * *"  # every day at midnight


jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete published images from the ghcr.io registry when untagged and older than a week
        uses: snok/container-retention-policy@v2
        with:
          image-names: brouberol/5esheets
          cut-off: A week ago UTC
          account-type: personal
          untagged-only: true
          token: ${{ secrets.GITHUB_TOKEN }}
