name: Run backend tests and checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Restore tooling cache
        uses: actions/cache@v3
        env:
          cache-name: checking-tooling-cache
        with:
          path: |
            .mypy_cache
            .ruff_cache
            .pytest_cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}

      - name: Install poetry
        run: python3 -m pip install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: make deps-python

      - name: Run unit tests
        run: make back-test

      - name: Run quality chekers
        run: make back-check

      - name: Lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
