name: Run frontend tests and checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: npm
          cache-dependency-path: dnd5esheets/front/package-lock.json

      - name: Install dependencies
        run: make deps-js

      - name: Run unit tests
        run: make front-test

      - name: Run quality chekers
        run: make front-check
