name: Run tests and checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: dnd5esheets/front/package-lock.json
      - name: Install dependencies
        run: |
          python -m pip install poetry
          make deps
      - name: Run unit tests
        run: make test

      - name: Run quality chekers
        run: make check
