name: Dependabot update requirements.txt
on: pull_request
permissions:
  contents: write
jobs:
  deps:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install poetry
      run: python3 -m pip install poetry

    - name: Create local changes
      run: poetry export -o requirements.txt

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author_name: "dependabot[bot]"
        author_email: "support@github.com"
        message: "Update requirements.txt"
        branch: "${{ github.head_ref }}"
